# Generated by Django 5.0.3 on 2024-03-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='orfer',
            new_name='order',
        ),
    ]
